set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "--target=i386-linux-gnu -m32 -fPIC")
set(CMAKE_CXX_FLAGS_INIT "--target=i386-linux-gnu -m32 -fPIC -fno-sized-deallocation")
set(CMAKE_ASM_FLAGS_INIT "--target=i386-linux-gnu -m32 -fPIC")
